### PR TITLE
Migrate from Yarn Classic to Yarn 3

### PR DESCRIPTION
**Pull request by wojtekmaj**
This is a major but low-effort change, so I've decided to start discussing about the change from actually doing it first. :D

### CODE REVIEW

**Comment by NickGerleman** [comment]
I'm a little mixed on this one, just because the RN ecosystem is largely still on yarn classic from my observation. The corepack bits may make that easier, but I am curious the opposing value we get, beyond being on the newer train.

**Comment by tido64** [comment]
FWIW, we've been using Yarn 3 for almost two years now without any issues:
image

**Comment by wojtekmaj** [comment]
> I'm a little mixed on this one

Thought so :) 

> just because the RN ecosystem is largely still on yarn classic from my observation.

Similarly to @tido64 - I'm maintaining 3 RN apps on Yarn 3 without any issues whatsoever. It's working fantastic for me.

> but I am curious the opposing value we get

There are many changes, but here's what I think is the most important for trivial (from repo arch point of view) project like this:
- Performance
- Less buggy behavior (Yarn Classic is a bit dated now!)
- Increased compatibility - Yarn ships with "portable shell" so e.g. env variables work without any hacks on Windows

**Comment by tido64** [comment]
I would also add better handling of network failures. We used to see issues all the time on CI, but they are mostly gone after the update.

**Review by NickGerleman — APPROVED** [review]
🤷‍♀️

**Comment by NickGerleman** [comment]
Needs fix for merge conflict

**Comment by wojtekmaj** [comment]
@NickGerleman Done :)

**Pull request merged**
